-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "testimonials" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "testimonials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"full_name" text NOT NULL,
	"company" text,
	"occupation" text,
	"review" text NOT NULL,
	"rating" smallint NOT NULL,
	"approved" boolean DEFAULT false NOT NULL,
	"avatar" text,
	"email" text,
	"session_id" text,
	CONSTRAINT "testimonials_email_key" UNIQUE("email")
);

*/